# Generated by Django 4.2 on 2025-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(help_text='Unique user identifier (auto-generated)', max_length=50, unique=True),
        ),
    ]
