# Generated by Django 4.2 on 2025-12-12 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(help_text='Stock symbol', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was taken')),
                ('quantity', models.PositiveIntegerField(help_text='Number of shares at this time')),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Stock price at this time', max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Total value (quantity × price)', max_digits=15)),
                ('user', models.ForeignKey(help_text='User who owns this stock', on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Snapshot',
                'verbose_name_plural': 'Stock Snapshots',
                'db_table': 'stock_snapshot',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was taken')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total portfolio value at this time (cash + holdings)', max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, help_text='Cash balance at this time', max_digits=15)),
                ('holdings_value', models.DecimalField(decimal_places=2, help_text='Total value of all holdings at this time', max_digits=15)),
                ('user', models.ForeignKey(help_text='User whose portfolio is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'db_table': 'portfolio_snapshot',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['user', 'stock', '-timestamp'], name='stock_snaps_user_id_b3db45_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', '-timestamp'], name='portfolio_s_user_id_f4fca1_idx'),
        ),
    ]
