# Generated by Django 4.2 on 2025-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0003_stocksnapshot_portfoliosnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realized_profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total realized profit/loss from closed positions', max_digits=15),
        ),
    ]
