# Generated by Django 4.2 on 2025-12-14 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0004_user_realized_profit_loss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(help_text='Stock ticker symbol', max_length=10)),
                ('signal_type', models.CharField(choices=[('index_addition', 'Index Addition'), ('index_removal', 'Index Removal'), ('price_target', 'Price Target Hit'), ('volume_spike', 'Volume Spike')], max_length=50)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('watch', 'Watch')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('index_name', models.CharField(blank=True, help_text='NASDAQ 100, S&P 500, etc', max_length=50, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'db_table': 'trading_signal',
                'ordering': ['-created_at'],
            },
        ),
    ]
