# Generated by Django 4.2 on 2025-12-16 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bot name', max_length=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Risk level: LOW, MEDIUM, HIGH', max_length=10)),
                ('duration', models.CharField(choices=[('SHORT', 'Short (1 week)'), ('MEDIUM', 'Medium (1 month)'), ('LONG', 'Long (3 months)'), ('CUSTOM', 'Custom')], default='MEDIUM', help_text='Trading duration', max_length=10)),
                ('initial_capital', models.DecimalField(decimal_places=2, help_text='Initial investment amount', max_digits=15)),
                ('current_capital', models.DecimalField(decimal_places=2, default=0.0, help_text='Current capital value', max_digits=15)),
                ('expected_return', models.DecimalField(decimal_places=2, default=0.0, help_text='Expected return percentage', max_digits=10)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Total profit/loss', max_digits=15)),
                ('total_trades', models.PositiveIntegerField(default=0, help_text='Total number of trades executed')),
                ('winning_trades', models.PositiveIntegerField(default=0, help_text='Number of winning trades')),
                ('losing_trades', models.PositiveIntegerField(default=0, help_text='Number of losing trades')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='ACTIVE', help_text='Bot status', max_length=10)),
                ('use_pivot', models.BooleanField(default=True, help_text='Use pivot point analysis')),
                ('use_prediction', models.BooleanField(default=True, help_text='Use next-day prediction')),
                ('use_screener', models.BooleanField(default=True, help_text='Use stock screener')),
                ('use_index_rebalancing', models.BooleanField(default=True, help_text='Use index rebalancing strategy')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When bot was created')),
                ('last_trade_at', models.DateTimeField(blank=True, help_text='Last trade timestamp', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this bot', on_delete=django.db.models.deletion.CASCADE, related_name='trading_bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Trading Bot',
                'verbose_name_plural': 'Auto Trading Bots',
                'db_table': 'auto_trading_bot',
                'ordering': ['-created_at'],
            },
        ),
    ]
